
services:
  web:
    build: ./backend
    command: /app/entrypoint.sh
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Porta local 3000 → Nginx servindo na porta 80
    depends_on:
      - web

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
